version: '3.4'

services:
  calculajuros.api:
    image: ${DOCKER_REGISTRY-}calculajurosapi
    build:
      context: .
      dockerfile: CalculaJuros.API/Dockerfile
    container_name: calculajuros_api
    ports:
      - 5600:443
      - 5601:80
